### ISSUE TITLE
Command Prompt must close

### ISSUE THREAD

**Issue by yahu1031** [YazeedAlKhalaf/Flutter_Installer#4] opened 2020-07-31 18:30 UTC
Greetings there,

when the installation process was cancelled by the user the command prompt that was opened ( at 25% process ) is not closing. that must be checked once.

https://drive.google.com/file/d/1xtxsWsBOOyGz8xOTDrlcJwKCxiN4h9FL/view?usp=sharing

thanks in advance.

**Comment by YazeedAlKhalaf** [comment] 2020-08-01 10:27
Okay I will look into it. Thanks for your notice 🙏

**Comment by YazeedAlKhalaf** [comment] 2020-08-01 11:14
I believe the problem is in `Process.run()` itself. I am researching on how to solve it. And I have also reached out to the package owner @tekartik 

GitHub Repo: https://github.com/tekartik/process_run.dart

**Comment by yahu1031** [comment] 2020-08-01 12:45
😅😅 I still see some issues that needs a fix and I will update you soon

**Comment by YazeedAlKhalaf** [comment] 2020-08-01 12:55
That's great! 😁✌

**Comment by yahu1031** [comment] 2020-08-01 14:10
@YazeedAlKhalaf I have a suggestion for this application downloading process. can I give it here?

**Comment by YazeedAlKhalaf** [comment] 2020-08-01 15:18
It is better to open a new issue. Sine an issue is meant to track one problem at a time.

**Comment by yahu1031** [comment] 2020-08-01 22:09
@YazeedAlKhalaf If possible please do read mail I have sent you. And delete this comment here after checking mail.

**Comment by YazeedAlKhalaf** [comment] 2020-08-19 18:56
@yahu1031 
It seems this is a Dart specific issue, we have to wait until it is solved. 
https://github.com/dart-lang/sdk/issues/39945

**Comment by YazeedAlKhalaf** [comment] 2020-10-15 07:33
@imReker gave his workaround here https://github.com/flutter/flutter/issues/47891#issuecomment-708850435 and it was really so helpful.

I have updated the `main.cpp` and the problem is fixed now. A new release will be soon up 🚀.

I feel safe to close this issue.

**Closed by YazeedAlKhalaf** 2020-10-15 07:33 UTC
Labels: bug
