### ISSUE TITLE
Downloading process is not aborting when clicked cancel

### ISSUE THREAD

**Issue by yahu1031** [YazeedAlKhalaf/Flutter_Installer#11] opened 2020-11-03 06:28 UTC
**Debug Console**

```console
Restarted application in 825ms.
flutter: 🐛  SharedPrefsService - (TRACE) LocalStorageService:_getFromDisk. key: theme_mode_flutter_installer value: ThemeMode.dark
flutter: 💡  InstallingViewModel - Install On Linux
flutter: 💡  InstallingViewModel - Installation Cancelled!
flutter: 💡  InstallingViewModel - Archive Name: flutter_linux_1.22.3-stable.tar.xz
flutter: 💡  InstallingViewModel - Temp Directory Name: flutter_installer
flutter: 💡  InstallingViewModel - Created Shell: Instance of 'Shell'
flutter: 💡  InstallingViewModel - Change Directory to Temp
flutter: 💡  InstallingViewModel - Change directory to flutter_installer
flutter: 💡  InstallingViewModel - Distro Name: parrot
4.10

flutter: 💡  InstallingViewModel - Started Download of "flutter_linux_1.22.3-stable.tar.xz" from "https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.22.3-stable.tar.xz"
```

**Procedure to reproduce**

![inout](https://user-images.githubusercontent.com/35523357/97955030-261e0400-1dcb-11eb-8d27-8225e763f8c3.gif)

[**video**](https://drive.google.com/file/d/1LomuASOz4zwkMcGJwt14GgzwqMvoXI_o/view?usp=sharing) for more refernce

This is a critical fix to do, add some critical tag :rofl:

**Comment by YazeedAlKhalaf** [comment] 2020-11-03 06:30
> This is a critical fix to do, add some critical tag 🤣

Sure 🚀

**Comment by YazeedAlKhalaf** [comment] 2021-03-03 15:38
Closing as duplicate of #9

**Closed by YazeedAlKhalaf** 2021-03-03 15:38 UTC
Labels: duplicate
